server:
  port: 8080  #API Gateway lÃ¤uft auf Port 8080
spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:

                #Example:
                #Request on: http://gateway:8080/kostal/status
                #Predicate: check, if /kostal/servie fits the pattern /kostal/**  --> /status
                #Filter: new path: http://localhost:8082/status

              - id: fronius-service
                uri: http://localhost:8081
                predicates:
                  - Path=/fronius/**
                filters:
                  - StripPrefix=1

              - id: kostal-service
                uri: http://localhost:8082
                predicates:
                  - Path=/kostal/**
                filters:
                  - StripPrefix=1

              - id: shelly-service
                uri: http://localhost:8083
                predicates:
                  - Path=/shelly/**
                filters:
                  - StripPrefix=1

              - id: forecasting-service
                uri: http://localhost:8084
                predicates:
                  - Path=/forecasting/**
                filters:
                  - StripPrefix=1

              - id: newsfeed-service
                uri: http://localhost:8086
                predicates:
                  - Path=/newsfeed/**
                filters:
                  - StripPrefix=1

              - id: weatherservice-service
                uri: http://localhost:8087
                predicates:
                  - Path=/weatherservice/**
                filters:
                  - StripPrefix=1

