server:
  port: 8080  #API Gateway l√§uft auf Port 8080
spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: fronius-service
              uri: http://localhost:8081
              predicates:
                - Path=/fronius/**
              filters:
                - StripPrefix=1
            - id: kostal-service
              uri: http://localhost:8082
              predicates:
                - Path=/kostal/**
              filters:
                - StripPrefix=1
